SSCS-10638-DeadLetterQueueAlert
hmcts/sscs-shared-infrastructure pull request #132
Opened 2022-06-13 12:59 UTC by rmurphy-hmcts

### JIRA link (if applicable) ###
SSCS-10638-DeadLetterQueueAlert

### Change description ###
Action group and alert metric added.
Ability to turn on/off metrics in tfvar files

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-06-13 13:16 UTC, reespozzi approved these changes

2022-06-14 13:40 UTC, MohammedHMCTS requested changes

2022-06-14 13:40 UTC, MohammedHMCTS commented on demo.tfvars
> +            values   = ["mohammeds-awesome-queue"]
Same here

2022-06-14 13:40 UTC, MohammedHMCTS commented on servicebus.tf
> +  depends_on = [module.evidenceshare-topic]
Not to sure if this is required?

2022-06-14 14:25 UTC, rmurphy-hmcts commented on servicebus.tf
> +  depends_on = [module.evidenceshare-topic]
This is required due to the topic needing to be created before the module can run. It has already been incorporated into master branch.

2022-06-16 08:30 UTC, thomaswatsonv1 approved these changes
Looks good!

2022-06-16 08:45 UTC, MohammedHMCTS approved these changes

2022-06-16 08:49 UTC, merged